#!/bin/sh
set -e

cd /var/www/html

# Create/Overwrite .env with system environment variables
echo "# Generated by Docker Entrypoint" > .env
printenv | grep -E '^(APP_|DB_|LOG_|MAIL_|SESSION_|QUEUE_|CACHE_|FILESYSTEM_|AWS_|VITE_)' >> .env || true

# If APP_KEY is not set, generate it
if ! grep -q "^APP_KEY=" .env || [ -z "$(grep "^APP_KEY=" .env | cut -d'=' -f2)" ]; then
  php artisan key:generate --force
fi

# Storage link (safe) — migrations are run separately via Render job or manually
php artisan storage:link || true

# Ensure SQLite database exists and has correct permissions
if [ "${DB_CONNECTION}" = "sqlite" ] || [ -z "${DB_CONNECTION}" ]; then
  touch database/database.sqlite
  chown www-data:www-data database/database.sqlite || true
  chmod 664 database/database.sqlite || true
fi

# Run migrations automatically
php artisan migrate --force

# Ensure permissions
chown -R www-data:www-data storage bootstrap/cache database || true

# Start php-fpm in background and nginx in foreground
php-fpm -D || true
nginx -g 'daemon off;'
